import "./globals.css";
import { Inter } from "next/font/google";
import { useLocale } from "next-intl";
import { notFound } from "next/navigation";
import ReduxProvider from "./components/ReduxProvider";
import MainWrapper from "./components/MainWrapper";
import { NextIntlClientProvider } from "next-intl";
const inter = Inter({ subsets: ["latin"] });

export const metadata = {
    title: "YoutubeQuiz",
    description: "Generated by create next app",
};

export default async function RootLayout({
    children,
    params,
}: {
    children: React.ReactNode;
    params: any;
}) {
    const locale = useLocale();

    if (params.locale !== locale) {
        notFound();
    }
    let messages;
    try {
        messages = (await import(`../../messages/${locale}.json`)).default;
    } catch (error) {
        notFound();
    }

    return (
        <NextIntlClientProvider locale={locale} messages={messages}>
            <ReduxProvider>
                <MainWrapper>{children}</MainWrapper>
            </ReduxProvider>
        </NextIntlClientProvider>
    );
}
